# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16b21d7f22f8e39f4516b9ad0d9592a4b5c33cd40df90244e1a5b9b477bb74b8aaa67c77a60ee79964fa3f74c762618311e5f19deda14e9b528f387a850a744d

test:
  secret_key_base: 1e09a8f74e7978e527148f96ba8c5ee556a4365e6640777e7f8117706b743faac2262d3e165044325d35dff2a623d66c6ecfb2b95012b83f391614cc1aa07b8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
